[package]
name = "vfs-glob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
udled = { git = "https://github.com/kildevaeld/udled-rs" }
vfs = { path = "../vfs" }
